%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1 

imu_topic: "/imu/data"
image0_topic: "/dalsa_gray/left/image_raw"
image1_topic: "/dalsa_gray/right/image_raw"
output_path: "/home/pesg/output/"

cam0_calib: "dalsa_cam0_pinhole_down.yaml"
cam1_calib: "dalsa_cam1_pinhole_down.yaml"
image_width: 960
image_height: 600
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.00375313,0.01609339,0.99986345,0.17517298,
                -0.99997267,-0.00642959,-0.00365005,0.13259005,
                  0.00636997,-0.99984982,0.01611708,0.0670137,
                  0.0,0.0,0.0,1.0]

#Multiple thread support
multiple_thread: 4        # origin 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time origin 0.04
max_num_iterations: 8  # max solver itrations, to guarantee real time origin 8
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       
# The raw calibrated imu intrinsics only take stationary properties into account, to conduct 
# real-world testing, some other processes will also happen, including temperature drift, motional effects, etc.
# So we recommend to increase the white_noise to several to 10x to relax these errors.
# Directly try the following params that we have successfully tested.
acc_n: 0.01          # accelerometer measurement noise standard deviation. 
gyr_n: 0.002         # gyroscope measurement noise standard deviation.     
acc_w: 0.00008        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.00003       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/pesg/output/pose_gragh/" # save and load path
save_image: 1                  # save image in pose graph for visualization prupose; you can close this function by setting 0 
